package com.puasnow.periodictable.models

data class Element(
    val isEmptySlot:Boolean=false,
    val appearance: String?=null,
    val atomic_mass: String?=null,
    val boil: Double?=null,
    val category: String?=null,
    val color: Any?=null,
    val cpkhex: String?=null,
    val density: Double?=null,
    val discovered_by: String?=null,
    val electron_affinity: Double?=null,
    val electron_configuration: String?=null,
    val electron_configuration_semantic: String?=null,
    val electronegativity_pauling: Double?=null,
    val ionization_energies: List<Double>?=null,
    val melt: Double?=null,
    val molar_heat: Double?=null,
    val name: String?=null,
    val named_by: String?=null,
    val number: String?=null,
    val period: Int?=null,
    val phase: String?=null,
    val shells: List<Int>?=null,
    val source: String?=null,
    val spectral_img: String?=null,
    val summary: String?=null,
    val symbol: String?=null,
    val xpos: Int?=null,
    val ypos: Int?=null,
    var fontColor: String?=null,
    var backgroundColor: String?=null
)